FROM golang:alpine

RUN set -eux; \
    apk add --no-cache \
        db-dev \
        g++ \
        gcc \
        git \
        make \
        putty
RUN go get github.com/golang/dep/cmd/dep

CMD ["go", "version"]
